// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDpFg_66lz--jfBK3PH9RTVQZEie9E31Q',
    appId: '1:390108455121:web:28fe3f1bea3737ec1aa5f0',
    messagingSenderId: '390108455121',
    projectId: 'barcodescanner-fd0db',
    authDomain: 'barcodescanner-fd0db.firebaseapp.com',
    storageBucket: 'barcodescanner-fd0db.appspot.com',
    measurementId: 'G-7LP57CCE2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbq0dS7hvkF1zZCuHkKkiCGXAhhTnlyd0',
    appId: '1:390108455121:android:91aedec078d714371aa5f0',
    messagingSenderId: '390108455121',
    projectId: 'barcodescanner-fd0db',
    storageBucket: 'barcodescanner-fd0db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBltBI9Zk3lczCZH-v5Z3faS1RU2r8FV3c',
    appId: '1:390108455121:ios:a6883d2fb7e1d1381aa5f0',
    messagingSenderId: '390108455121',
    projectId: 'barcodescanner-fd0db',
    storageBucket: 'barcodescanner-fd0db.appspot.com',
    iosBundleId: 'com.example.barcodeScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBltBI9Zk3lczCZH-v5Z3faS1RU2r8FV3c',
    appId: '1:390108455121:ios:a6883d2fb7e1d1381aa5f0',
    messagingSenderId: '390108455121',
    projectId: 'barcodescanner-fd0db',
    storageBucket: 'barcodescanner-fd0db.appspot.com',
    iosBundleId: 'com.example.barcodeScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDpFg_66lz--jfBK3PH9RTVQZEie9E31Q',
    appId: '1:390108455121:web:a6a1e4ccfd482d431aa5f0',
    messagingSenderId: '390108455121',
    projectId: 'barcodescanner-fd0db',
    authDomain: 'barcodescanner-fd0db.firebaseapp.com',
    storageBucket: 'barcodescanner-fd0db.appspot.com',
    measurementId: 'G-SWNXDHMXYN',
  );
}
